(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var l,m="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function p(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=p(this),r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var t;a:{var u={a:!0},v={};try{v.__proto__=u;t=v.a;break a}catch(a){}t=!1}r=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var w=r;function x(a,b,c){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return c}};var y=/^(\d+|\d*\.\d+)px$/i,z=/^(\d+|\d*\.\d+)em$/i;function B(){this.g=[];this.i=10;this.h=!0;this.j=!1}function C(a,b){b.forEach(function(c){if(a.g.every(function(e){return e.element!=c})&&!c.hasAttribute("gwd-dont-fit")){var d=D(a,c);a.g.push(d)}})}function E(a){a.g.forEach(function(b){F(b)});a.g=[]}function G(a,b){b.forEach(function(c){for(var d=0;d<a.g.length;d++){var e=a.g[d];if(e.element==c){F(e);a.g.splice(d,1);break}}})}
function F(a){null!=a.u&&(a.element.style.fontSize=a.u);if(null!=a.m){for(;a.element.firstChild;)a.element.removeChild(a.element.lastChild);for(var b=a.m.cloneNode(!0);0<b.childNodes.length;)a.element.appendChild(b.firstChild)}}
function D(a,b){var c=window.getComputedStyle(b),d=b.style.fontSize,e=b.cloneNode(!0),f={clientWidth:b.clientWidth,clientHeight:b.clientHeight},h=!1,g=a.h;b.hasAttribute("data-gwd-fit-font-size")&&(g="false"!=b.getAttribute("data-gwd-fit-font-size"));var k=H(c.fontSize);c=k||24;var n=parseInt(b.getAttribute("gwd-min-font-size-px"),10);n=isFinite(n)?n:a.i;g=g&&(!k||k>n)&&(b.scrollHeight>f.clientHeight||b.scrollWidth>f.clientWidth);k=!1;if(g){var A=H(window.getComputedStyle(b).fontSize);null!=A&&(h=
I(a,b,A));c=J(b,f,n,c);-1==c?(b.style.fontSize=n+"px",k=!0):b.style.fontSize=c+"px"}c=a.j;b.hasAttribute("gwd-fitting-truncate")&&(c="false"!=b.getAttribute("gwd-fitting-truncate"));c&&(k||b.scrollHeight>f.clientHeight||b.scrollWidth>f.clientWidth)&&(K(a,b,f,null),h=!0);return{element:b,u:g?d:null,m:h?e:null}}function J(a,b,c,d){return L(a,b,c,d,function(e,f){e.style.fontSize=f+"px"})}
function K(a,b,c,d){if(d&&1!=d.nodeType&&3!=d.nodeType)return!1;var e=d?d:b;if(3==e.nodeType||0==e.children.length){var f=e.textContent;if(""==f)return!1;if(e!=b){e.textContent="\u2026";if(b.scrollHeight>c.clientHeight||b.scrollWidth>c.clientWidth)return!1;e.textContent=f}a=L(b,c,0,f.length,function(g,k){e.textContent=f.slice(0,k)+"\u2026"});e.textContent=-1==a?"":f.slice(0,a)+"\u2026";return-1!=a}for(d=e.childNodes.length-1;0<=d;d--){var h=e.childNodes[d];if(K(a,b,c,h))return!0;e.removeChild(h)}return!1}
function L(a,b,c,d,e){d=Math.floor(d);for(var f=-1,h=0;50>h;){var g=Math.floor((c+d)/2);e(a,g);if(a.scrollHeight>b.clientHeight||a.scrollWidth>b.clientWidth){if(g==c)return f;d=g-1}else{f=g;if(c==d)return f;c=g+1}h++}return-1}
function I(a,b,c){if(b.hasAttribute("gwd-dont-fit"))return!1;for(var d=!1,e=b.children.length,f=0;f<e;f++){var h=b.children[f],g=window.getComputedStyle(h).fontSize,k=H(g);if(k)h.style.fontSize=k/c+"em",d=!0;else if(g=(g=z.exec(g||""))?parseFloat(g[1]):null)k=g*c;else return!1;h=I(a,h,k);d=d||h}return d}function H(a){return(a=y.exec(a||""))?parseFloat(a[1]):null};function M(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=window.setTimeout(function(){c=null;b&&(a(),b=!1)},100))}};var N="color font-family font-size font-style font-weight font-stretch text-align white-space".split(" "),O=/[^\s\xA0]/;function P(a){this.i=a;this.g=new WeakMap;this.h=new WeakMap}function Q(a,b){if(a.g.get(b)){b.ownerDocument.compareDocumentPosition(b)&Node.DOCUMENT_POSITION_DISCONNECTED||R(a,b);var c=document.createElement("gwd-attached");b.appendChild(c);var d=function(){c.removeEventListener("attached",d);R(a,b);b.removeChild(c)};c.addEventListener("attached",d)}}
function R(a,b){var c=a.g.get(b),d=a.h.get(b)||{};if(c){c.l.style.display="none";b.insertBefore(c.l,b.firstChild);try{G(a.i,[b]);for(var e=getComputedStyle(c.parent),f=0;f<N.length;f++){var h=N[f],g=e.getPropertyValue(h);!d.hasOwnProperty(h)&&g&&b.style.setProperty(h,g,"")}b.removeAttribute("gwd-dont-fit");C(a.i,[b])}finally{b.removeChild(c.l)}}};var S=["data-gwd-fit-font-size","fit-font-size-for-selector","gwd-fitting-truncate","gwd-min-font-size-px"];function T(){var a=HTMLElement.call(this)||this;a.g=new B;a.j=":not(*)";a.i=new P(a.g);a.o=a.B.bind(a);a.h=a.A.bind(a);a.s=M(a.v.bind(a));return a}var U=HTMLElement;T.prototype=m(U.prototype);T.prototype.constructor=T;if(w)w(T,U);else for(var V in U)if("prototype"!=V)if(Object.defineProperties){var W=Object.getOwnPropertyDescriptor(U,V);W&&Object.defineProperty(T,V,W)}else T[V]=U[V];l=T.prototype;
l.connectedCallback=function(){document.addEventListener("pagetransitionstart",this.o);document.addEventListener("adinitialized",this.h)};l.disconnectedCallback=function(){document.removeEventListener("pagetransitionstart",this.o);document.removeEventListener("adinitialized",this.h);window.removeEventListener("resize",this.s,!1)};
l.attributeChangedCallback=function(a,b,c){switch(a){case "data-gwd-fit-font-size":this.g.h=x(this,a,!0);break;case "fit-font-size-for-selector":this.j=c||":not(*)";break;case "gwd-min-font-size-px":b=this.g;a=parseInt(this.getAttribute(a),10);isNaN(a)&&(a=10);b.i=a;break;case "gwd-fitting-truncate":this.g.j=x(this,a,!1)}};l.A=function(){document.removeEventListener("adinitialized",this.h);this.refitAll();window.addEventListener("resize",this.s,!1)};
l.B=function(a){"gwd-pagedeck"==a.target.tagName.toLowerCase()&&this.fit(X(this,a.target))};l.saveInitialText=function(a){for(var b=this.i,c=document.createNodeIterator(a,NodeFilter.SHOW_TEXT,null,!1),d=null,e;e=c.nextNode();)if(O.test(e.textContent)){d=e;break}if(d&&(c=d.parentNode,c!=a)){a.setAttribute("gwd-dont-fit","");for(d=c;d.parentNode!=a;)d=d.parentNode;b.g.set(a,{l:d,parent:c})}};l.applyStylePreservation=function(a){Q(this.i,a)};
l.saveStyleOverride=function(a,b,c){var d=this.i,e=d.h.get(a)||{};e[b]=c;d.h.set(a,e)};l.fit=function(a){C(this.g,a||X(this,document))};function X(a,b){return Array.prototype.slice.call(b.querySelectorAll(a.j)).filter(function(c){return c!==a})}l.v=function(){this.refitAll()};l.refitAll=function(){E(this.g);this.fit()};q.Object.defineProperties(T,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return S}}});customElements.define("gwd-text-helper",T);}).call(this);
