#ifndef CBUFFER_BUFFERRAWSEGMENTSTOCONTOUR_VIEW_INCLUDED
#define CBUFFER_BUFFERRAWSEGMENTSTOCONTOUR_VIEW_INCLUDED

    #include "../ComputeAddressingDefs.hlsl"
    #define BITS_OFFSET_BUFFERRAW_VISIBLESEGTOSEG BITS_WORD_OFFSET
    uint CBuffer_BufferRawVisibleSegToSeg_AddrAt(uint id)
    {
        return (id << BITS_OFFSET_BUFFERRAW_VISIBLESEGTOSEG);
    }

#endif /* CBUFFER_BUFFERRAWSEGMENTSTOCONTOUR_VIEW_INCLUDED */
