#ifndef CBUFFER_BUFFERRAWPEREDGE_VIEW_INCLUDED
#define CBUFFER_BUFFERRAWPEREDGE_VIEW_INCLUDED

#include "../ComputeAddressingDefs.hlsl"

#ifdef KERNEL_CONTOUR_COMPACTION
#   define BITS_OFFSET_BUFFER_RAW_PER_EDGE BITS_BLOCK_OFFSET
#else 
#   define BITS_OFFSET_BUFFER_RAW_PER_EDGE BITS_WORD_OFFSET
#endif

#define CBuffer_BufferRawPerEdge_AddrAt(id) (id << BITS_OFFSET_BUFFER_RAW_PER_EDGE)

#endif /* CBUFFER_BUFFERRAWPEREDGE_VIEW_INCLUDED */
