#ifndef CBUFFER_EVLIST_VIEW_INCLUDED
#define CBUFFER_EVLIST_VIEW_INCLUDED

#define BITS_OFFSET_EVLIST (BITS_WORD_OFFSET + 1)
#define CBuffer_EVList_AddrAt(id) (id << BITS_OFFSET_EVLIST)

#endif /* CBUFFER_EVLIST_VIEW_INCLUDED */
